### ISSUE TITLE
Error when running truffle migrate — compile-all 

### ISSUE THREAD

**Issue by tara519** [trufflesuite/truffle-migrate#35]
Hi

I am trying to run the code in 
https://medium.com/coinmonks/build-a-dapp-using-ethereum-and-angular-6-a404fbf3c08d

When I run the command 
$ truffle migrate — compile-all — reset — network ganache
I get the following error

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Function.Config.load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:386:1)
    at Function.Config.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:375:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/migrate.js:176:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command.js:106:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:52:1)
    at __webpack_require__ (/usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap e6bbe05105385f7e6e8f:19:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap e6bbe05105385f7e6e8f:65:1
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:71:10)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
Truffle v5.0.22 (core: 5.0.22)
Node v12.4.0
Varshas-MacBook-Air:helloworld vsehgal$ truffle migrate — compile-all — reset — network ganache
/Users/vsehgal/helloworld/truffle-config.js:40
host : ‘localhost’,
       

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Function.Config.load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:386:1)
    at Function.Config.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:375:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/migrate.js:176:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command.js:106:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:52:1)
    at __webpack_require__ (/usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap e6bbe05105385f7e6e8f:19:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap e6bbe05105385f7e6e8f:65:1
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:71:10)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11

Please any ideas for what I am doing wrong

**Comment by nourmhamdi** [comment]
i have the same problem. did you fix it please ??
